# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_linklist_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='linklist',
        ),
    ]
